version: '3.7'

services:
  php:
    image: 'akeneo/pim-php-dev:8.1'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      COMPOSER_HOME: '/var/www/.composer'
      PHP_IDE_CONFIG: 'serverName=pim-docker-cli'
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: 'client_host=172.17.0.1'
      BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID:-client_id}'
      BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN:-client_token}'
      EXPERIMENTAL_TEST_DATABASE: '${EXPERIMENTAL_TEST_DATABASE:-0}'
    volumes:
      - './:/srv/pim'
      - '${HOST_COMPOSER_HOME:-~/.composer}:/var/www/.composer'
    working_dir: '/srv/pim'
    command: 'php'
    user: 'www-data'
    init: true
    networks:
      - 'pim'

  httpd:
    image: 'akeneo/pim-php-dev:8.1'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      BEHAT_TMPDIR: '/srv/pim/var/cache/tmp'
      BEHAT_SCREENSHOT_PATH: '/srv/pim/var/tests/screenshots'
      PHP_IDE_CONFIG: 'serverName=pim-docker-web'
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: 'client_host=172.17.0.1'
      BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID:-client_id}'
      BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN:-client_token}'
    volumes:
      - './:/srv/pim'
      - './docker/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './docker/akeneo.conf:/usr/local/apache2/conf/vhost.conf:ro'
    working_dir: '/srv/pim'
    ports:
      - '${DOCKER_PORT_HTTP:-8888}:80'
    networks:
      - 'pim'

  node:
    image: 'akeneo/node:18'
    environment:
      YARN_CACHE_FOLDER: '/home/node/.yarn'
      CYPRESS_CACHE_FOLDER: '/home/node/.cypress'
    volumes:
      - './:/srv/pim'
      - '~/.cache/yarn:/home/node/.yarn'
      # - '${HOST_CYPRESS_CACHE_FOLDER:-~/.cache/Cypress}:/home/node/.cypress'
    working_dir: '/srv/pim'
    networks:
      - 'pim'

  mysql:
    image: 'mysql:8.0.30'
    command: '--default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: '${APP_DATABASE_USER}'
      MYSQL_DATABASE: '${APP_DATABASE_NAME}'
      MYSQL_PASSWORD: '${APP_DATABASE_PASSWORD}'
    volumes:
      - './docker/initdb.d:/docker-entrypoint-initdb.d:ro'
      # - ./var/mysql:/var/lib/mysql
    # ports:
      # - '${DOCKER_PORT_MYSQL:-33006}:3306'
    networks:
      - 'pim'

  elasticsearch:
    image: 'elastic/elasticsearch:8.4.2'
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms1g -Xmx1g}'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      indices.id_field_data.enabled: 'true'
    # ports:
      # - '${DOCKER_PORT_ELASTICSEARCH:-9210}:9200'
    networks:
      - 'pim'

  object-storage:
    image: 'minio/minio:RELEASE.2021-09-15T04-54-25Z'
    entrypoint: '/bin/sh -c "mkdir -p /data/archive /data/catalog /data/jobs /data/category /data/catalogs_mapping && minio server --console-address :9091 /data"'
    environment:
      MINIO_ACCESS_KEY: 'AKENEO_OBJECT_STORAGE_ACCESS_KEY'
      MINIO_SECRET_KEY: 'AKENEO_OBJECT_STORAGE_SECRET_KEY'

    ports:
      # - '${DOCKER_PORT_OBJECT_STORAGE:-9090}:9000'
      - '${DOCKER_PORT_OBJECT_STORAGE_CONSOLE:-9091}:9091'
    networks:
      - 'pim'

  autoinstrumenter:
    image: grafana/beyla:latest
    pid: "service:httpd"
    privileged: true
    environment:
      BEYLA_PRINT_TRACES: true
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4318"
      # BEYLA_SYSTEM_WIDE: true
      BEYLA_BPF_WAKEUP_LEN: 1
      BEYLA_SKIP_GO_SPECIFIC_TRACERS: true
      BEYLA_DISCOVERY_POLL_INTERVAL: "500ms"
      # BEYLA_BPF_TRACK_REQUEST_HEADERS: "true"
      # BEYLA_OPEN_PORT: 80,9000
      # BEYLA_EXECUTABLE_NAME: php-fpm
      # OTEL_SERVICE_NAME: "akeneo"
      # BEYLA_PROMETHEUS_PORT: 8999
    command:
      - -config
      - /etc/beyla.conf
    volumes:
      - ./beyla.yaml:/etc/beyla.conf
      # - /sys/kernel/security:/sys/kernel/security
    networks:
      - compose_otlp_belya
      - pim

  # beyla-elastic:
  #   image: grafana/beyla:latest
  #   pid: "service:elasticsearch"
  #   privileged: true
  #   environment:
  #     # BEYLA_PRINT_TRACES: true
  #     OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4318"
  #     BEYLA_OPEN_PORT: 9200
  #     OTEL_SERVICE_NAME: "elasticsearch"
  #     BEYLA_BPF_TRACK_REQUEST_HEADERS: "true"
  #     # BEYLA_PROMETHEUS_PORT: 8999
  #   # command:
  #     # - -config
  #     # - /etc/beyla.conf
  #   # volumes:
  #     # - ./beyla.yaml:/etc/beyla.conf
  #   networks:
  #     - compose_otlp_belya
  #     - pim

  # beyla-minio:
  #   image: grafana/beyla:latest
  #   pid: "service:object-storage"
  #   privileged: true
  #   environment:
  #     # BEYLA_PRINT_TRACES: true
  #     OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4318"
  #     BEYLA_OPEN_PORT: 9000,9091
  #     OTEL_SERVICE_NAME: "minio"
  #     # BEYLA_PROMETHEUS_PORT: 8999
  #   # command:
  #     # - -config
  #     # - /etc/beyla.conf
  #   # volumes:
  #     # - ./beyla.yaml:/etc/beyla.conf
  #   networks:
  #     - compose_otlp_belya
  #     - pim


networks:
  pim:
  compose_otlp_belya:
    external: {}
