services:
  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - ./shared/config.alloy:/etc/alloy/config.alloy
    ports:
      - 12345:12345
    networks:
      - otlp_belya

  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo
    networks:
      - otlp_belya

  tempo:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./shared/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    # ports:
    #   - "14268:14268"  # jaeger ingest
    #   - "3200:3200"   # tempo
    #   - "9095:9095" # tempo grpc
    #   - "4317:4317"  # otlp grpc
    #   - "4318:4318"  # otlp http
    #   - "9411:9411"   # zipkin
    depends_on:
      - init
    networks:
      - otlp_belya

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=remote-write-receiver
    volumes:
      - ./shared/prometheus.yaml:/etc/prometheus.yaml
    # ports:
    #   - "9090:9090"
    networks:
      - otlp_belya

  grafana:
    image: grafana/grafana:11.0.0
    volumes:
      - ./shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./shared/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ../dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "3000:3000"
    networks:
      - otlp_belya

networks:
  otlp_belya: {}
  # jaeger:
  #   image: jaegertracing/all-in-one:1.51
  #   ports:
  #     - '6831:6831'
  #     - '16686:16686'
