otlp-up:
	docker compose -f docker-compose.yaml up -d --remove-orphans

otlp-stop:
	docker compose -f docker-compose.yaml stop

youtrack-up:
	docker compose -f youtrack/docker-compose.yaml up -d --remove-orphans

youtrack-stop:
	docker compose -f youtrack/docker-compose.yaml stop
