services:
  youtrack:
    image: jetbrains/youtrack:2024.2.35942
    volumes:
      - './youtrack/data:/opt/youtrack/data'
      - './youtrack/conf:/opt/youtrack/conf'
      - './youtrack/logs:/opt/youtrack/logs'
      - './youtrack/backups:/opt/youtrack/backups'
    ports:
      - 8080:8080
    networks:
      - compose_otlp_belya

  autoinstrumenter:
    image: grafana/beyla:main
    pid: "service:youtrack"
    privileged: true
    environment:
      # BEYLA_PRINT_TRACES: true
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4318"
      # BEYLA_OPEN_PORT: 8080
      # OTEL_SERVICE_NAME: "youtrack"
      # BEYLA_PROMETHEUS_PORT: 8999
    command:
      - -config
      - /etc/beyla.conf
    volumes:
      - ./beyla.yaml:/etc/beyla.conf
    networks:
      - compose_otlp_belya

networks:
  compose_otlp_belya:
    external: {}
