version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: demo-nginx
    ports:
      - 3333:3330
    volumes:
      - ./configs/:/etc/nginx
    depends_on:
      gotestserver:
        condition: service_started
      javatestserver:
        condition: service_started
      rusttestserver:
        condition: service_started
    networks:
      - compose_otlp_belya

  # Beyla for NGINX
  nginxbeyla:
    image: grafana/beyla:latest
    volumes:
      - ./configs/:/configs
      - ./system/sys/kernel/security:/sys/kernel/security
    container_name: demo-nginxbeyla
    privileged: true
    network_mode: "service:nginx"
    pid: "service:nginx"
    environment:
      BEYLA_CONFIG_PATH: "/configs/beyla-config.yml"
      BEYLA_PRINT_TRACES: "true"
      BEYLA_OPEN_PORT: "3330"
      BEYLA_SERVICE_NAMESPACE: "demo"
      OTEL_SERVICE_NAME: "demo-nginx"
      BEYLA_LOG_LEVEL: "DEBUG"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4318"
    depends_on:
      nginx:
        condition: service_started


  # Go test server
  # Test server source can be found at test/integration/components/testserver
  gotestserver:
    image: ghcr.io/grafana/beyla-demo/greeting-go/0.0.1
    container_name: demo-gotestserver
    #ports:
    #  - "8084:8080"
    networks:
      - compose_otlp_belya


  # Beyla for Java Spring Boot 3.0 GraalVM Native Image
  gobeyla:
    image: grafana/beyla:latest
    volumes:
      - ./configs/:/configs
      - ./system/sys/kernel/security:/sys/kernel/security
    container_name: demo-gobeyla
    privileged: true
    network_mode: "service:gotestserver"
    pid: "service:gotestserver"
    environment:
      BEYLA_CONFIG_PATH: "/configs/beyla-config.yml"
      BEYLA_PRINT_TRACES: "true"
      BEYLA_OPEN_PORT: "8080"
      BEYLA_SERVICE_NAMESPACE: "demo"
      OTEL_SERVICE_NAME: "demo-go-service"
      BEYLA_LOG_LEVEL: "DEBUG"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4318"
    depends_on:
      gotestserver:
        condition: service_started


  # Java Spring Boot 3.0 GraalVM Native Image test server
  # Test server source can be found at test/integration/components/javatestserver
  javatestserver:
    image: ghcr.io/grafana/beyla-demo/greeting-graalvm-native/0.0.1
    container_name: demo-javatestserver
    #ports:
    #  - "8085:8085"
    networks:
      - compose_otlp_belya


  # Beyla for Java Spring Boot 3.0 GraalVM Native Image
  javabeyla:
    image: grafana/beyla:latest
    volumes:
      - ./configs/:/configs
      - ./system/sys/kernel/security:/sys/kernel/security
    container_name: demo-javabeyla
    privileged: true
    network_mode: "service:javatestserver"
    pid: "service:javatestserver"
    environment:
      BEYLA_CONFIG_PATH: "/configs/beyla-config.yml"
      BEYLA_PRINT_TRACES: "true"
      BEYLA_OPEN_PORT: "8085"
      BEYLA_SERVICE_NAMESPACE: "demo"
      OTEL_SERVICE_NAME: "demo-graalvm-native-service"
      BEYLA_LOG_LEVEL: "DEBUG"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4318"
    depends_on:
      javatestserver:
        condition: service_started


  # Rust Actix test server
  # Test server source can be found at test/integration/components/rusttestserver
  rusttestserver:
    image: ghcr.io/grafana/beyla-demo/greeting-actix-rust/0.0.1
    container_name: demo-rusttestserver
    #ports:
    #  - "8086:8090"
    networks:
      - compose_otlp_belya


  # Beyla for Rust Actix
  rustbeyla:
    image: grafana/beyla:latest
    volumes:
      - ./configs/:/configs
      - ./system/sys/kernel/security:/sys/kernel/security
    container_name: demo-rustbeyla
    privileged: true
    network_mode: "service:rusttestserver"
    pid: "service:rusttestserver"
    environment:
      BEYLA_CONFIG_PATH: "/configs/beyla-config.yml"
      BEYLA_PRINT_TRACES: "true"
      BEYLA_OPEN_PORT: "8090"
      BEYLA_SERVICE_NAMESPACE: "demo"
      OTEL_SERVICE_NAME: "demo-rust-service"
      BEYLA_LOG_LEVEL: "DEBUG"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4318"
    depends_on:
      rusttestserver:
        condition: service_started

networks:
  compose_otlp_belya:
    external: {}
